name: 📦 Release & Publish to npm

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read
  issues: read
  id-token: write

jobs:
  release:
    name: 🚀 Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Get next version
        id: version
        uses: reecetech/version-increment@v2024.10.1
        with:
          scheme: conventional_commits
          release_branch: main

      - name: Bump version in package.json
        if: steps.version.outputs.version != steps.version.outputs.current-version
        run: |
          sed -i "s/\"version\": *\".*\"/\"version\": \"${{ steps.version.outputs.version }}\"/" package.json

      - name: Commit and Tag new version
        if: steps.version.outputs.version != steps.version.outputs.current-version
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore: release v${{ steps.version.outputs.version }}"
          tag: v${{ steps.version.outputs.version }}

      - name: Generate CHANGELOG
        if: steps.version.outputs.version != steps.version.outputs.current-version
        id: changelog
        uses: requarks/changelog-action@v1.10.2
        with:
          fromTag: v${{ steps.version.outputs.current-version }}
          toTag: v${{ steps.version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        if: steps.version.outputs.version != steps.version.outputs.current-version
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.version.outputs.version }}
          name: Version ${{ steps.version.outputs.version }}
          body: ${{ steps.changelog.outputs.changes }}
          makeLatest: true

      - name: Build package
        run: bun run build

      - name: Publish to npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          bunx npm-cli-login -u tracktor -p $NPM_TOKEN -e contact@tracktor.fr
          bun publish --access public
